# Reference: https://build-cpp.github.io/cmkr/cmake-toml


[project]
name = "template-clang"

[target.template]
type = "executable"
include-directories = [
    "../include/base",
    "../include/toolbox",
]
headers = ["src/**.h"]
sources = [
    "src/**.cpp"
]
compile-features = ["cxx_std_20"]
link-libraries = ["glfw3.lib", "yourgame.lib"]

